apiVersion: v1
kind: Plugin
metadata:
  author: sheetung
  name: DataCardPlugin
  repository: 'https://github.com/sheetung/DataCardPlugin'
  version: 1.0.0
  description:
    en_US: 流量卡查询
    zh_Hans: 流量卡查询
  label:
    en_US: DataCardPlugin
    zh_Hans: DataCardPlugin
  icon: assets/icon.png
spec:
  config:
    - name: llkshop_id
      type: string
      label:
        en_US: 'LLKShop ID'
        zh_Hans: 'LLKShop ID'
      required: true
      default: '3abcd2e80b9b4694'
    - name: use_forward
      type: boolean
      label:
        en_US: 'Enable Forwarding Merge'
        zh_Hans: '是否启用合并转发（仅适配OneBot）'
      required: false
      default: true
    - name: onebot_api_url
      type: string
      show_if:
        field: use_forward
        operator: 'eq'
        value: true
      label:
        en_US: 'OneBot HTTP Server URL'
        zh_Hans: 'OneBot HTTP 服务器 地址'
      required: false
      default: 'http://127.0.0.1:3000'
    - name: onebot_access_token
      type: string
      show_if:
        field: use_forward
        operator: 'eq'
        value: true
      label:
        en_US: 'OneBot HTTP Server Access Token'
        zh_Hans: 'OneBot HTTP 服务器访问令牌'
      required: true
      default: ''
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: DataCardPlugin
