apiVersion: v1
kind: Plugin
metadata:
  author: sheetung
  name: DataCardPlugin
  repository: 'https://github.com/sheetung/DataCardPlugin'
  version: 0.1.0
  description:
    en_US: 流量卡查询
    zh_Hans: 流量卡查询
  label:
    en_US: DataCardPlugin
    zh_Hans: DataCardPlugin
  icon: assets/icon.png
spec:
  config:
    - name: llkshop_id
      type: string
      label:
        en_US: 'LLKShop ID'
        zh_Hans: 'LLKShop ID'
      required: true
      default: '3abcd2e80b9b4694'
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: DataCardPlugin
